# Generated by Django 5.2.12 on 2026-04-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("company", models.CharField(blank=True, max_length=150)),
                ("job_title", models.CharField(blank=True, max_length=150)),
                ("course_name", models.CharField(default="GenAIBIZ", max_length=200)),
                ("message", models.TextField(blank=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("is_paid", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-registered_at"],
            },
        ),
    ]
